[package]
name = "gamescope-wayland-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
wayland-backend = "0.3.2"
wayland-client = "0.31.1"
wayland-scanner = "0.31.0"
